### ISSUE TITLE
Change the "Not for resale, Faggot" boot screen

### ISSUE THREAD

**Issue by loic2665** [Huawei-LTE-routers-mods/Huawei_E5372_mod_fw#3]
Hi,

I was wondering if there was a way to change the boot screen image.
I personnaly think that is a bit rude to the user. I think there is other way to show that
the device should not be sold to non tech people user after this upgrade.

Showing a version number, with a little text live "Mod Version x.x.x - Not to sale" at the bottom,
with a customized logo could make the experience a bit better. After all this is the first thing you
see when you turn on the device.

Take care,
Thanks.

**Comment by ValdikSS** [comment]
I was thinking on the phrasing for at least 3 months, and haven't thought of something more polite but as straight as current phrase.

See, in Russia accusing for being a faggot is a pretty strong affront. Consider the following: somebody trying to sell the router with this firmware installed. "Not for resale" text on boot screen tells absolutely nothing, at least its Russian version.
— "Why is it not for resale", the buyer would think, — "I'm buying it right now, how could it be not for resale? What does that mean?".
Not for resale phrase is so weak it won't even lead you to think about it. However, if the router calls you a faggot, that's, at least, will tell your brain "WHOA, stop, why the router calls me a faggot? Seems very fishy."
Russian sellers won't sell anything which call you a faggot, because it greatly increases risk of being punched in the face.

I gave routers to my parents and they are OK with that. I call the router "a faggot", and the firmware "a faggot firmware". My friends giggle every time. For me, it turned out better and funnier than expected.

I'm totally against people who use the firmware only to bypass internet sharing restrictions (to change IMEI/TTL) to save 300-400 rubles per month (≈$4-5). These are complete faggots to me. And the sellers of 'configured sets' are faggots².

**Comment by loic2665** [comment]
Oh, yes, I didn't know that was going THAT deep. 

Thanks for your answer.
Take care. :-) 

Loïc.
